version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
    container_name: project3-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:80"   # host:container -> open https://project8-hkio.onrender.com for the app
    networks:
      - projectnet

  backend:
    build: ./backend
    container_name: project3-backend
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/project3db
    volumes:
      - ./backend:/app
    networks:
      - projectnet

  db:
    image: postgres:16
    container_name: project3-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: project3db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - projectnet

volumes:
  pgdata:

networks:
  projectnet:
    driver: bridge
